export const pricingPlans = [
  {
    id: "individual",
    title: "Individual",
    icon: "https://cdn.builder.io/api/v1/image/assets/d1565a3d38674b2f92e823900af9b856/fd1d7293803e4a6f3e6089b3dc0cdab74f9c6ed3",
    price: "$99",
    period: "/month",
    features: [
      "Featurely as your User, UXR, Designer, Front End Engineer",
      "Collaborate in natural language",
      "1 seat",
      "10 users",
      "Priority Support",
      "7-day free trial",
    ],
    background: "bg-deep-space-blue",
  },
  {
    id: "team",
    title: "Team",
    icon: "https://cdn.builder.io/api/v1/image/assets/d1565a3d38674b2f92e823900af9b856/487cb8ee6d2ac4711c1c321fa2074cf13ac4075f",
    price: "$499",
    period: "/month",
    features: [
      "Featurely as your User, UXR, Designer, Front End Engineer",
      "Collaborate in natural language",
      "5 seats",
      "50 users",
      "Dedicated Support",
      "Dedicated team workspace",
      "Share and Collaborate",
      "7-day free trial",
    ],
    background: "bg-midnight-purple",
  },
  {
    id: "enterprise",
    title: "Enterprise",
    icon: "https://cdn.builder.io/api/v1/image/assets/d1565a3d38674b2f92e823900af9b856/b6bc3612de5ff053b99a7734b60102bdda8d20c2",
    price: "Custom",
    period: "",
    features: [
      "Featurely as your User, UXR, Designer, Front End Engineer",
      "Collaborate in natural language",
      "Unlimited seats",
      "Access to Custom Featurely users",
      "Unlimited seats",
      "Security & support",
      "Deploy in your virtual private cloud (VPC)",
      "Dedicated account team Custom terms",
    ],
    background: "bg-charcoal-black",
  },
];
